site_name: MkDocs Documentation Example

theme:
  name: material
  features:
    - content.code.annotate
    - toc.integrate
    
plugins:
   - search

markdown_extensions:
   - admonition
   - codehilite
   - def_list
   - fenced_code
   - markdown_include_lines.main:
        base_path: docs/
   - markdown_include.include:
        base_path: docs/
   - pymdownx.details
   - pymdownx.highlight:
       use_pygments: true
       linenums: true
       linenums_style: table
   - pymdownx.inlinehilite
   - pymdownx.snippets
   - pymdownx.superfences
   - pymdownx.tabbed:
       alternate_style: true

extra_css:
  - css/pygments.css
